feat: добавить БД и функционал бронирования и комментариев
Seetochka/java-shareit pull request #2
Opened 2022-07-25 11:59 UTC by Seetochka

2022-07-25 16:46 UTC, EugeneLenkevich requested changes
Привет, Светлана, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-25 16:46 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getName() != null) {
Можно это записать, кстати, вот так

Optional.ofNullable(itemDto.getName(), (name)-> itemUpdated.setName(name))

или примерно так

Optional.ofNullable(itemDto.getName(), itemUpdated::setName(name))

2022-07-25 16:46 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userService.getUserById(userId);
Такой код выглядит немного странно, get-метод предполагает что метод что-то вернет, а что тут происходит не ясно без заглядывания в реализацию, подошли бы методы наподобие isExist :)
Вообще, можно поменьше использовать исключения, они могут усложнять жизни когда их много, ничего страшного если метод репозитория возвращает null, а еще лучше Optional (Optional.empty() в случае если записи нет)

2022-07-25 16:46 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemMapper.toItem(getItemById(userId, itemId));
На уровне сервиса можно пользоваться только непосредственными сущностями, зачем нам постоянно делать такие конверсии, dto нужен чтобы спрятать детали реализации доменного слоя и передать вовне данные в более удобном для внешних сервисов виде :)

2022-07-25 16:46 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return commentMapper.toCommentDto(commentRepository.save(commentCreated));
Три раза пришлось данные переложить туда-сюда :)

2022-07-25 19:38 UTC, Seetochka commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getName() != null) {
Исправила

2022-07-25 19:38 UTC, Seetochka commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        userService.getUserById(userId);
Исправила

2022-07-25 19:44 UTC, Seetochka commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemMapper.toItem(getItemById(userId, itemId));
Да, сначала не понятно было где лучше пользоваться DTO, а когда в прошлой домашке уже сделала в сервисах, Марк написал пост что можно в контроллерах делать все преобразования

> Потому что сервисы часто вызывают методы друг друга, и могут работать немного по другому. Но иногда действительно можно сделать как ты описываешь. В моем понимании dto это обычно dto уровня контроллеров. То есть это сущность, которой оперируют исключительно контроллеры.

В этой уже вышло так что мне нужны были сущности из других сервисов, а возвращали они DTO, оттуда и вышли все эти преобразования, сейчас решила все таки попробовать убрать всю работу с DTO в контроллеры

2022-07-25 19:45 UTC, Seetochka commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return commentMapper.toCommentDto(commentRepository.save(commentCreated));
Исправила

2022-07-26 03:31 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Item item = itemMapper.toItem(getItemById(userId, itemId));
Ну на самом деле тут противоречия особо и нет, я про то же самое :)
Неоднозначно выразился, под внешними  сервисами подразумеваю не сами наши сервисы, а те слои что идут выше, это могут быть не всегда контроллеры, а например обработчики JMS. Dto нам нужны как раз на границе нашего приложения, в тех же контроллерах, вот примерно так

![image](https://user-images.githubusercontent.com/109306643/180916663-ae52284d-23e9-4a6b-8253-47a35ee6470c.png)

А есть еще понятие гексагональной архитектуры. На картинке ниже dto логично было бы расположить в синем слое

PS это на самом деле все вопрос сложный и холиварный, на практике бывает как попало (в зависимости от того насколько архитектор разобрался в вопросе)

https://habr.com/ru/company/otus/blog/492076/
![image](https://user-images.githubusercontent.com/109306643/180916812-9509dc01-b174-4f4d-9134-4e146346d12f.png)

2022-07-26 03:31 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-07-26 06:31 UTC, merged